#!/bin/bash

echo "Nginx 설정을 업데이트하려면 다음 명령을 실행하세요:"
echo ""
echo "1. nginx 설정 파일 복사:"
echo "   sudo cp /home/starian/lilys-ai-clone/nginx-correct.conf /etc/nginx/sites-available/default"
echo ""
echo "2. nginx 설정 테스트:"
echo "   sudo nginx -t"
echo ""
echo "3. nginx 재시작:"
echo "   sudo systemctl reload nginx"
echo ""
echo "현재 서버 상태:"
echo "- 프론트엔드: http://localhost:3000 (정상)"
echo "- 백엔드 API: http://localhost:5001 (정상)"
echo ""
echo "문제: nginx가 프론트엔드를 3003 포트로 프록시하고 있지만, 실제로는 3000 포트에서 실행 중입니다."